"""Generate plain pytest test skeletons from behavior features."""

from __future__ import annotations

import json
from pathlib import Path

from specweave.behavior.common import (
    canonical_test_path,
    display_path,
    iter_feature_scenarios,
    scenario_identifier,
    test_function_name,
)
from specweave.config import PYTEST_TESTS_DIR
from specweave.gherkin.lint import collect_feature_files
from specweave.gherkin.model import Feature, Scenario
from specweave.gherkin.parser import parse_feature

MAX_GENERATED_LINE_LENGTH = 88


def _docstring_lines(scenario: Scenario) -> list[str]:
    lines = [f"{scenario.keyword}: {scenario.title}."]
    if scenario.description:
        lines.append("")
        lines.extend(scenario.description.splitlines())
    if scenario.steps:
        lines.append("")
        lines.extend(f"{step.keyword} {step.text}" for step in scenario.steps)
    return lines


def _split_literal(value: str, max_part_length: int) -> list[str]:
    if len(value) <= max_part_length:
        return [value]

    parts: list[str] = []
    remaining = value
    while len(remaining) > max_part_length:
        split_at = max(
            remaining.rfind("/", 0, max_part_length + 1),
            remaining.rfind("-", 0, max_part_length + 1),
            remaining.rfind("_", 0, max_part_length + 1),
        )
        if split_at <= 0:
            split_at = max_part_length
        else:
            split_at += 1
        parts.append(remaining[:split_at])
        remaining = remaining[split_at:]
    if remaining:
        parts.append(remaining)
    return parts


def _assignment_lines(name: str, value: str) -> list[str]:
    single = f"{name} = {json.dumps(value)}"
    if len(single) <= MAX_GENERATED_LINE_LENGTH:
        return [single]
    max_part_length = MAX_GENERATED_LINE_LENGTH - 6
    return [
        f"{name} = (",
        *[f"    {json.dumps(part)}" for part in _split_literal(value, max_part_length)],
        ")",
    ]


def _keyword_string_arg_lines(name: str, value: str, *, indent: str) -> list[str]:
    single = f"{indent}{name}={json.dumps(value)},"
    if len(single) <= MAX_GENERATED_LINE_LENGTH:
        return [single]
    max_part_length = MAX_GENERATED_LINE_LENGTH - len(indent) - 6
    return [
        f"{indent}{name}=(",
        *[
            f"{indent}    {json.dumps(part)}"
            for part in _split_literal(value, max_part_length)
        ],
        f"{indent}),",
    ]


def generate_pytest_skeleton(feature: Feature, feature_path: Path) -> str:
    """Render *feature* as a plain pytest skeleton module."""

    feature_ref = display_path(feature_path)
    lines: list[str] = [
        '"""Plain pytest enforcement generated by SpecWeave."""',
        "",
        "from __future__ import annotations",
        "",
        "import pytest",
        "",
        *_assignment_lines("SPECWEAVE_FEATURE", feature_ref),
        "",
    ]

    existing_names: set[str] = set()
    for rule, scenario in iter_feature_scenarios(feature):
        scenario_ref = scenario_identifier(scenario)
        function_name = test_function_name(scenario.title, existing_names)
        existing_names.add(function_name)
        lines.append("@pytest.mark.specweave(")
        lines.append("    feature=SPECWEAVE_FEATURE,")
        lines.extend(_keyword_string_arg_lines("scenario", scenario_ref, indent="    "))
        if rule is not None and rule.title:
            lines.extend(_keyword_string_arg_lines("rule", rule.title, indent="    "))
        lines.append(")")
        lines.append(f"def {function_name}() -> None:")
        doc = _docstring_lines(scenario)
        lines.append(f'    """{doc[0]}')
        for line in doc[1:]:
            lines.append(f"    {line}")
        lines.append('    """')
        for step in scenario.steps:
            phase = {
                "Given": "Arrange",
                "When": "Act",
                "Then": "Assert",
            }.get(step.keyword, "Continue")
            lines.append(f"    # {phase}: {step.keyword} {step.text}")
        lines.append("    raise NotImplementedError(")
        lines.append('        "Implement behavior from " + SPECWEAVE_FEATURE')
        lines.append("    )")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_pytest_skeleton(
    feature_path: Path,
    *,
    out: Path | None = None,
    tests_dir: Path = PYTEST_TESTS_DIR,
) -> Path:
    """Write a pytest skeleton for *feature_path* and return the output path."""

    feature = parse_feature(
        feature_path.read_text(encoding="utf-8"),
        source_path=feature_path,
    )
    output_path = out or canonical_test_path(feature_path, tests_dir=tests_dir)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        generate_pytest_skeleton(feature, feature_path),
        encoding="utf-8",
    )
    return output_path


def generate_from_paths(
    *,
    feature_path: Path | None = None,
    features_dir: Path | None = None,
    out: Path | None = None,
    tests_dir: Path = PYTEST_TESTS_DIR,
) -> list[Path]:
    """Generate one or more pytest skeletons."""

    if feature_path is not None:
        return [write_pytest_skeleton(feature_path, out=out, tests_dir=tests_dir)]

    root = features_dir or Path("specs/behavior/features")
    outputs: list[Path] = []
    for candidate in collect_feature_files((root,)):
        outputs.append(write_pytest_skeleton(candidate, tests_dir=tests_dir))
    return outputs
