@area-brownfield @feature-pytest-to-gherkin-discovery
Feature: Discover behavior specs from existing pytest tests

  SpecWeave supports brownfield adoption by drafting reviewable Gherkin from
  existing pytest tests without claiming that generated behavior is final.

  Rule: Generate candidate specs from pytest

    @bdd-generate-gherkin-from-tests
    Example: Generate a feature from a pytest test file
      Given a pytest file contains test functions
      When I run specweave create gherkin --from-tests tests/test_login.py
      Then SpecWeave writes a feature under specs/behavior/features
      And each discovered test function becomes one scenario
      And each scenario receives a stable @bdd-* tag

    @bdd-generate-gherkin-groups-by-file
    Example: Generated features are grouped by source test file
      Given pytest tests exist in multiple test files
      When I run specweave create gherkin --from-tests for all files
      Then SpecWeave creates one feature per test file
      And nested test paths become behavior areas

    @bdd-generate-gherkin-marks-review-needed
    Example: Generated behavior is clearly marked for human review
      Given SpecWeave generates a feature from pytest code
      When the feature is written
      Then the feature includes @generated
      And generated scenarios include @needs-review

    @bdd-generate-gherkin-preserves-manual-files
    Example: Manual feature files are not overwritten
      Given a target feature file exists and was not generated by SpecWeave
      When I run specweave create gherkin without --force
      Then SpecWeave skips that file
      And SpecWeave reports a warning

    @bdd-generate-gherkin-force-overwrites
    Example: Force allows regenerating a feature
      Given a target feature file exists
      When I run specweave create gherkin --force
      Then SpecWeave overwrites the generated target
