"""SpecWeave project initialization."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from specweave.config import SpecWeavePaths, render_default_config

_BEHAVIOR_README_CONTENT = """\
# Behavior specifications

This directory is managed by SpecWeave.

Canonical feature files live under:

```text
features/<area>/<feature>.feature
```

Use:

```bash
specweave doctor
specweave review specs
specweave create gherkin --from-tests tests
```

Rules:

- keep one feature per file;
- group feature files by area;
- use stable `@bdd-*` tags for scenarios/examples;
- use `@ac-*` tags only when validating a task acceptance criterion;
- do not rely on scenario titles as validation keys.
"""


@dataclass(frozen=True)
class InitResult:
    """Result of a ``specweave init`` run."""

    config_path: Path
    created: tuple[Path, ...]
    existing: tuple[Path, ...]
    skipped: tuple[Path, ...]
    warnings: tuple[str, ...]


def _readme_is_specweave_managed(path: Path) -> bool:
    """Check whether an existing README was generated by SpecWeave."""
    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False
    return "This directory is managed by SpecWeave." in content


def _resolve_paths(paths: SpecWeavePaths, root: Path) -> SpecWeavePaths:
    """Resolve all relative paths under *root*."""
    return SpecWeavePaths(
        specs_root=root / paths.specs_root,
        features_dir=root / paths.features_dir,
        behavior_readme=root / paths.behavior_readme,
        manifest=root / paths.manifest,
        tests_dir=root / paths.tests_dir,
        reports_dir=root / paths.reports_dir,
        state_dir=root / paths.state_dir,
        evidence_dir=root / paths.evidence_dir,
        reports_state_dir=root / paths.reports_state_dir,
        mapping_dir=root / paths.mapping_dir,
    )


def run_init(
    *,
    config_path: Path = Path(".specweave.toml"),
    spelling: str = "behavior",
    force: bool = False,
    dry_run: bool = False,
    project_root: Path | None = None,
) -> InitResult:
    """Run ``specweave init`` and return an ``InitResult``.

    Parameters
    ----------
    config_path:
        Target config file path (e.g. ``.specweave.toml`` or ``specweave.toml``).
    spelling:
        ``"behavior"`` or ``"behaviour"``.
    force:
        When true, overwrite existing generated files.
    dry_run:
        When true, compute the result but write nothing.
    project_root:
        Root directory to resolve relative paths against. Defaults to cwd.
    """
    from specweave.config import SpecWeaveConfig

    config_text = render_default_config(spelling=spelling)
    config = SpecWeaveConfig(spelling=spelling)

    if project_root is None:
        project_root = Path.cwd()

    raw_paths = (
        config.paths if config.spelling == spelling else _paths_for_spelling(spelling)
    )
    paths = _resolve_paths(raw_paths, project_root)

    created: list[Path] = []
    existing: list[Path] = []
    skipped: list[Path] = []
    warnings: list[str] = []

    # Config file
    if config_path.exists() and not force:
        existing.append(config_path)
        warnings.append(
            f"Config {config_path} already exists; use --force to overwrite."
        )
    elif config_path.exists() and force:
        existing.append(config_path)
        if not dry_run:
            config_path.write_text(config_text, encoding="utf-8")
    else:
        created.append(config_path)
        if not dry_run:
            config_path.parent.mkdir(parents=True, exist_ok=True)
            config_path.write_text(config_text, encoding="utf-8")

    # Directories to create
    dirs = [
        paths.state_dir,
        paths.reports_state_dir,
        paths.evidence_dir,
        paths.mapping_dir,
        paths.specs_root,
        paths.features_dir,
        paths.reports_dir,
    ]

    for d in dirs:
        if d.exists():
            existing.append(d)
        else:
            created.append(d)
            if not dry_run:
                d.mkdir(parents=True, exist_ok=True)

    # Features gitkeep
    gitkeep_path = paths.features_dir / ".gitkeep"
    if config.gitkeep:
        if gitkeep_path.exists():
            existing.append(gitkeep_path)
        else:
            created.append(gitkeep_path)
            if not dry_run:
                gitkeep_path.touch()

    # README
    readme_path = paths.behavior_readme
    if readme_path.exists():
        if not _readme_is_specweave_managed(readme_path):
            skipped.append(readme_path)
            warnings.append(
                f"README {readme_path} has non-SpecWeave content;"
                " skipping. Use --force to overwrite."
            )
        else:
            existing.append(readme_path)
            if force and not dry_run:
                readme_path.write_text(_BEHAVIOR_README_CONTENT, encoding="utf-8")
    else:
        created.append(readme_path)
        if not dry_run:
            readme_path.parent.mkdir(parents=True, exist_ok=True)
            readme_path.write_text(_BEHAVIOR_README_CONTENT, encoding="utf-8")

    return InitResult(
        config_path=config_path,
        created=tuple(created),
        existing=tuple(existing),
        skipped=tuple(skipped),
        warnings=tuple(warnings),
    )


def init_result_to_dict(result: InitResult) -> dict:
    """Convert an ``InitResult`` to a JSON-serialisable dict."""
    return {
        "schema_version": 1,
        "command": "init",
        "status": "ok",
        "config_path": str(result.config_path),
        "created": [str(p) for p in result.created],
        "existing": [str(p) for p in result.existing],
        "skipped": [str(p) for p in result.skipped],
        "warnings": list(result.warnings),
    }


def _paths_for_spelling(spelling: str) -> SpecWeavePaths:
    spec_segment = f"specs/{spelling}"
    report_segment = f"reports/{spelling}"

    return SpecWeavePaths(
        specs_root=Path(spec_segment),
        features_dir=Path(f"{spec_segment}/features"),
        behavior_readme=Path(f"{spec_segment}/README.md"),
        manifest=Path(f"{spec_segment}/manifest.json"),
        reports_dir=Path(report_segment),
    )
